[package]
name = "chronicli"
version = "0.3.0"
authors = ["IOTA Stiftung"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
backstage = { git = "https://github.com/iotaledger/backstage.git", tag = "0.1.1"}
chronicle = { path = "../chronicle" }
chronicle-common = { path = "../chronicle-common" }
chronicle-broker = { path = "../chronicle-broker" }
scylla = { git = "https://github.com/iotaledger/scylla.rs.git", tag = "0.1.1" }
clap = { version = "2.33", features = ["yaml"] }
tokio = "1.5"
tokio-tungstenite = "0.14"
futures = "0.3"
url = "2.2"
serde_json = "1.0"
anyhow = "1.0"
regex = "1.4.5"