[package]
name = "chronicle-api"
version = "0.3.0"
authors = ["Alex Coats <alexandcoats@gmail.com>"]
edition = "2018"

[lib]
name = "chronicle_api"
path = "src/lib.rs"

[dependencies]
chronicle-common = { path = "../chronicle-common" }
chronicle-storage = { path = "../chronicle-storage" }
scylla-cql = { git = "https://github.com/iotaledger/scylla.rs.git", tag = "0.1.1" }
backstage = { git = "https://github.com/iotaledger/backstage.git", tag = "0.1.1"}
bee-rest-api = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
bee-message = { git = "https://github.com/iotaledger/bee.git", branch = "dev", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-trait = "0.1"
log = "0.4"
rocket = { git = "https://github.com/SergioBenitez/Rocket.git", rev = "e4c2324", optional = true }
hex = "0.4"
futures = "0.3"
anyhow = "1.0"
thiserror = "1.0"
bincode = "1.3"
tokio = "1.5"

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket.git"
rev = "e4c2324"
default-features = false
optional = true
features = ["json"]

[features]
default = ["rocket_listener"]
rocket_listener = ["rocket", "rocket_contrib/json"]
