[package]
name = "chronicle-filter"
version = "0.3.0"
authors = ["IOTA Stiftung"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chronicle-storage = { path = "../chronicle-storage" }