[package]
name = "chronicle-storage"
version = "0.1.0"
authors = ["Chronicle developers"]
edition = "2018"

[dependencies]
bee-ternary = { git = "https://github.com/Alex6323/bee-p", branch = "master"}
chronicle-common = { path = "../chronicle-common" }
chronicle-cql = { path = "../chronicle-cql" }
futures = "0.3"
tokio = { version = "0.2", features = ["fs", "macros", "stream", "sync", "net", "io-util", "rt-threaded", "time"] }
tokio-tungstenite = "0.10"
rand = "0.7"
cdrs = "2.2.4"
cdrs_helpers_derive = "0.1.0"
reqwest = "0.10"
indicatif = "0.14"
sha2 = "0.8"
