[package]
name = "chronicle-storage"
version = "0.2.1-alpha"
authors = ["IOTA Stiftung"]
edition = "2018"
license = "APACHE 2.0"
homepage = "https://docs.iota.org/docs/chronicle/1.1/overview"
repository = "https://github.com/iotaledger/chronicle.rs"

[dependencies]
chronicle-common = { path = "../chronicle-common" }
chronicle-cql = { path = "../chronicle-cql" }
futures = "0.3"
tokio = { version = "0.2", features = ["fs", "macros", "stream", "sync", "net", "io-util", "rt-threaded", "time"] }
tokio-native-tls = "0.1.0"
tokio-tungstenite = "0.10"
rand = "0.7"
sha2 = "0.8"
url = "2.1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4.8"
