[package]
name = "chronicle-cql"
version = "0.1.0"
authors = ["Chronicle developers"]
edition = "2018"

[dependencies]
rand = "0.7"
lz4 = "1.23"
snap = "1.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "murmur3_benchmark"
harness = false
