[package]
name = "permanode-common"
version = "0.1.0"
authors = ["IOTA Stiftung"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
permanode-api = { path = "../permanode-api" }
permanode-storage = { path = "../permanode-storage" }
permanode-broker = { path = "../permanode-broker" }
serde = { version = "1.0", features = ["derive"] }
ron = "0.6.4"

[dev-dependencies]
maplit = "1.0.2"
url = { version = "2", features = ["serde"] }