name: Build docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setting env
        run: echo "GIT_SHA=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

      - name: Setting up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setting up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push container
        run: docker build . -f Dockerfile -t iotaledger/chronicle:$GIT_SHA -t iotaledger/chronicle:latest --platform linux/amd64 --push
